# Generated by Django 5.0.7 on 2024-07-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ApiUser',
        ),
    ]
