# Generated by Django 5.0.7 on 2024-07-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_apiuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiuser',
            old_name='user',
            new_name='user_id',
        ),
    ]
