# Generated by Django 5.0.7 on 2024-07-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_apiuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='user_id',
        ),
    ]
