# Generated by Django 5.0.7 on 2024-07-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_apiuser_email_remove_apiuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='buy_history',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='sell_history',
        ),
    ]
